apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-00-2d2110a5ed1f/my-repository/hello-cloudbuild:v2.0
        ports:
        - containerPort: 8080
